package compiler_test

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/alexvinola/stemma-cli/internal/adapters"
	"github.com/alexvinola/stemma-cli/internal/canonical"
	"github.com/alexvinola/stemma-cli/internal/compiler"
	"github.com/alexvinola/stemma-cli/internal/diagnostics"
	"github.com/alexvinola/stemma-cli/internal/profiles"
	"github.com/alexvinola/stemma-cli/internal/workspace"
)

// updateGolden regenerates fixture files. Golden files are never rewritten by
// an ordinary test run: regenerating them is an explicit developer action.
//
//	go test ./internal/compiler -run TestGolden -update-golden
var updateGolden = flag.Bool("update-golden", false, "rewrite golden fixture files")

const testdataDir = "../../testdata"

// materialize copies a fixture input tree into a temporary workspace.
func materialize(t *testing.T, src string) *workspace.Workspace {
	t.Helper()
	root := t.TempDir()
	err := filepath.WalkDir(src, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		dest := filepath.Join(root, rel)
		if d.IsDir() {
			return os.MkdirAll(dest, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		return os.WriteFile(dest, data, 0o644)
	})
	if err != nil {
		t.Fatalf("materialize %s: %v", src, err)
	}
	ws, err := workspace.Open(root, workspace.DefaultLimits())
	if err != nil {
		t.Fatalf("open workspace: %v", err)
	}
	return ws
}

// compareOrUpdate compares generated bytes with a golden file.
func compareOrUpdate(t *testing.T, path string, got []byte) {
	t.Helper()
	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("missing golden file %s: %v\nRun: go test ./internal/compiler -run TestGolden -update-golden", path, err)
	}
	if !bytes.Equal(want, got) {
		t.Errorf("golden mismatch for %s\n--- want ---\n%s\n--- got ---\n%s", path, want, got)
	}
}

// diagnosticsJSON renders diagnostics as a stable golden document.
func diagnosticsJSON(t *testing.T, diags []diagnostics.Diagnostic) []byte {
	t.Helper()
	sorted := append([]diagnostics.Diagnostic{}, diags...)
	diagnostics.Sort(sorted)
	if sorted == nil {
		sorted = []diagnostics.Diagnostic{}
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(sorted); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// mappingsJSON renders the projection report as a stable golden document.
func mappingsJSON(t *testing.T, mappings []adapters.ProjectionMapping) []byte {
	t.Helper()
	type row struct {
		EntityID    string   `json:"entityId"`
		EntityType  string   `json:"entityType"`
		Outcome     string   `json:"outcome"`
		Files       []string `json:"files"`
		Activation  string   `json:"activation"`
		Explanation string   `json:"explanation"`
	}
	rows := make([]row, 0, len(mappings))
	for _, m := range mappings {
		rows = append(rows, row{
			EntityID: m.EntityID, EntityType: string(m.EntityType), Outcome: string(m.Outcome),
			Files: m.Files, Activation: adapters.ScopeLabel(m.Activation), Explanation: m.Explanation,
		})
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(rows); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// fixtureCases lists the case directories of a provider fixture directory.
func fixtureCases(t *testing.T, provider string) []string {
	t.Helper()
	dir := filepath.Join(testdataDir, provider)
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read fixtures for %s: %v", provider, err)
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			out = append(out, e.Name())
		}
	}
	sort.Strings(out)
	return out
}

// TestGoldenImportAndExport is the provider fixture suite: it imports each
// fixture, compares the canonical project and diagnostics, then compiles every
// requested target and compares the generated files.
func TestGoldenImportAndExport(t *testing.T) {
	providers := map[string]canonical.TargetFormat{
		"copilot": canonical.TargetCopilot,
		"claude":  canonical.TargetClaude,
		"codex":   canonical.TargetCodex,
		"kiro":    canonical.TargetKiro,
	}
	names := make([]string, 0, len(providers))
	for name := range providers {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		format := providers[name]
		for _, caseName := range fixtureCases(t, name) {
			t.Run(name+"/"+caseName, func(t *testing.T) {
				caseDir := filepath.Join(testdataDir, name, caseName)
				ws := materialize(t, filepath.Join(caseDir, "input"))
				ctx := context.Background()

				res, err := compiler.Import(ctx, ws, compiler.ImportOptions{
					Format:      format,
					ProjectID:   "prj_fixture",
					ProjectName: "Fixture",
				})
				if err != nil {
					t.Fatalf("import: %v", err)
				}
				data, err := canonical.MarshalProject(res.Project)
				if err != nil {
					t.Fatal(err)
				}
				compareOrUpdate(t, filepath.Join(caseDir, "expected-project.json"), data)
				compareOrUpdate(t, filepath.Join(caseDir, "expected-diagnostics.json"),
					diagnosticsJSON(t, res.Diagnostics))

				compileTargets(t, ctx, caseDir, res.Project, ws)
			})
		}
	}
}

// TestGoldenCanonical compiles hand-authored canonical projects. These cover
// shapes no importer can produce, such as exclude patterns and disabled rules.
func TestGoldenCanonical(t *testing.T) {
	for _, caseName := range fixtureCases(t, "canonical") {
		t.Run(caseName, func(t *testing.T) {
			caseDir := filepath.Join(testdataDir, "canonical", caseName)
			data, err := os.ReadFile(filepath.Join(caseDir, "project.json"))
			if err != nil {
				t.Fatal(err)
			}
			project, err := canonical.UnmarshalProject(data)
			if err != nil {
				t.Fatalf("decode fixture project: %v", err)
			}
			if diags := canonical.Validate(project); diagnostics.HasBlocking(diags) {
				t.Fatalf("fixture project is invalid: %+v", diags)
			}
			ws, err := workspace.Open(t.TempDir(), workspace.DefaultLimits())
			if err != nil {
				t.Fatal(err)
			}
			compileTargets(t, context.Background(), caseDir, project, ws)
		})
	}
}

// compileTargets compiles every "expected-<target>" directory in a case.
func compileTargets(
	t *testing.T, ctx context.Context, caseDir string, project canonical.Project, ws *workspace.Workspace,
) {
	t.Helper()
	entries, err := os.ReadDir(caseDir)
	if err != nil {
		t.Fatal(err)
	}
	var targets []string
	for _, e := range entries {
		if e.IsDir() && strings.HasPrefix(e.Name(), "expected-") {
			targets = append(targets, strings.TrimPrefix(e.Name(), "expected-"))
		}
	}
	// When updating, compile every implemented target so new fixtures appear.
	if *updateGolden {
		targets = []string{"github-copilot", "claude", "codex", "kiro"}
	}
	sort.Strings(targets)

	for _, target := range targets {
		format := canonical.TargetFormat(target)
		profile := profiles.Default(format)
		if data, err := os.ReadFile(filepath.Join(caseDir, "profile-"+target+".json")); err == nil {
			profile, err = profiles.Unmarshal(data)
			if err != nil {
				t.Fatalf("decode profile for %s: %v", target, err)
			}
		}
		result, err := compiler.Compile(ctx, project, compiler.CompileOptions{
			Target:  format,
			Profile: profile,
		})
		if err != nil {
			t.Fatalf("compile %s: %v", target, err)
		}
		outDir := filepath.Join(caseDir, "expected-"+target)
		if *updateGolden {
			_ = os.RemoveAll(outDir)
		}
		for _, f := range result.Files {
			compareOrUpdate(t, filepath.Join(outDir, filepath.FromSlash(f.Path)), f.Content)
		}
		compareOrUpdate(t, filepath.Join(caseDir, "expected-"+target+"-mappings.json"),
			mappingsJSON(t, result.Mappings))
		compareOrUpdate(t, filepath.Join(caseDir, "expected-"+target+"-diagnostics.json"),
			diagnosticsJSON(t, result.Diagnostics))

		// Every generated file must be present in the fixture, and the fixture
		// must contain nothing extra.
		if !*updateGolden {
			assertSameFileSet(t, outDir, result.Files, target)
		}
		_ = ws
	}
}

func assertSameFileSet(t *testing.T, dir string, files []adapters.GeneratedFile, target string) {
	t.Helper()
	want := map[string]struct{}{}
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		rel, rerr := filepath.Rel(dir, path)
		if rerr != nil {
			return rerr
		}
		want[filepath.ToSlash(rel)] = struct{}{}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		delete(want, f.Path)
	}
	for extra := range want {
		t.Errorf("target %s: fixture contains %s but the compiler did not generate it", target, extra)
	}
}
