package compiler_test

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/alexvinola/stemma-cli/internal/adapters"
	"github.com/alexvinola/stemma-cli/internal/canonical"
	"github.com/alexvinola/stemma-cli/internal/compiler"
	"github.com/alexvinola/stemma-cli/internal/diagnostics"
	"github.com/alexvinola/stemma-cli/internal/profiles"
	"github.com/alexvinola/stemma-cli/internal/store"
	"github.com/alexvinola/stemma-cli/internal/workspace"
)

// updateGolden regenerates fixture files. Golden files are never rewritten by
// an ordinary test run: regenerating them is an explicit developer action.
//
//	go test ./internal/compiler -run TestGolden -update-golden
var updateGolden = flag.Bool("update-golden", false, "rewrite golden fixture files")

const testdataDir = "../../testdata"

// materialize copies a fixture input tree into a temporary workspace.
func materialize(t *testing.T, src string) *workspace.Workspace {
	t.Helper()
	root := t.TempDir()
	err := filepath.WalkDir(src, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		dest := filepath.Join(root, rel)
		if d.IsDir() {
			return os.MkdirAll(dest, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		return os.WriteFile(dest, data, 0o644)
	})
	if err != nil {
		t.Fatalf("materialize %s: %v", src, err)
	}
	ws, err := workspace.Open(root, workspace.DefaultLimits())
	if err != nil {
		t.Fatalf("open workspace: %v", err)
	}
	return ws
}

// compareOrUpdate compares generated bytes with a golden file.
func compareOrUpdate(t *testing.T, path string, got []byte) {
	t.Helper()
	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("missing golden file %s: %v\nRun: go test ./internal/compiler -run TestGolden -update-golden", path, err)
	}
	if !bytes.Equal(want, got) {
		t.Errorf("golden mismatch for %s\n--- want ---\n%s\n--- got ---\n%s", path, want, got)
	}
}

// diagnosticsJSON renders diagnostics as a stable golden document.
func diagnosticsJSON(t *testing.T, diags []diagnostics.Diagnostic) []byte {
	t.Helper()
	sorted := append([]diagnostics.Diagnostic{}, diags...)
	diagnostics.Sort(sorted)
	if sorted == nil {
		sorted = []diagnostics.Diagnostic{}
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(sorted); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// mappingsJSON renders the projection report as a stable golden document.
func mappingsJSON(t *testing.T, mappings []adapters.ProjectionMapping) []byte {
	t.Helper()
	type row struct {
		EntityID    string   `json:"entityId"`
		EntityType  string   `json:"entityType"`
		Outcome     string   `json:"outcome"`
		Files       []string `json:"files"`
		Activation  string   `json:"activation"`
		Explanation string   `json:"explanation"`
	}
	rows := make([]row, 0, len(mappings))
	for _, m := range mappings {
		rows = append(rows, row{
			EntityID: m.EntityID, EntityType: string(m.EntityType), Outcome: string(m.Outcome),
			Files: m.Files, Activation: adapters.ScopeLabel(m.Activation), Explanation: m.Explanation,
		})
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(rows); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// compareProjectTree compares the on-disk layout of an imported project with
// the golden tree under "expected-project/".
func compareProjectTree(t *testing.T, caseDir string, project canonical.Project) {
	t.Helper()
	encoded, err := store.EncodeProject(project)
	if err != nil {
		t.Fatalf("encode project: %v", err)
	}
	root := filepath.Join(caseDir, "expected-project")
	if *updateGolden {
		if err := os.RemoveAll(root); err != nil {
			t.Fatal(err)
		}
	}
	paths := make([]string, 0, len(encoded.Files))
	for rel := range encoded.Files {
		paths = append(paths, rel)
	}
	sort.Strings(paths)
	for _, rel := range paths {
		// ".stemma/" is stripped: the golden tree mirrors the project, not the
		// directory it happens to live in.
		golden := filepath.Join(root, filepath.FromSlash(strings.TrimPrefix(rel, ".stemma/")))
		compareOrUpdate(t, golden, encoded.Files[rel])
	}
	if *updateGolden {
		return
	}
	var extra []string
	err = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, rerr := filepath.Rel(root, path)
		if rerr != nil {
			return rerr
		}
		key := ".stemma/" + filepath.ToSlash(rel)
		if _, ok := encoded.Files[key]; !ok {
			extra = append(extra, key)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range extra {
		t.Errorf("fixture contains %s but the importer did not produce it", e)
	}
}

// goldenCases is the coverage registry, shared by tests and make golden.
// Missing expected files must fail a test, never select fewer targets.
// See docs/testing.md for the reason each case/destination is retained.
type goldenCase struct {
	name            string
	targets         []canonical.TargetFormat
	snapshotProject bool
}

func goldenCases() []goldenCase {
	copilot, claude, codex, kiro := canonical.TargetCopilot, canonical.TargetClaude, canonical.TargetCodex, canonical.TargetKiro
	all := []canonical.TargetFormat{copilot, claude, codex, kiro}
	return []goldenCase{
		{"canonical/brace-globs", all, false},
		{"canonical/comma-in-pattern", all, false},
		{"canonical/exclude-and-disabled", all, false},
		{"claude/basic", all, true},
		{"claude/brace-globs", []canonical.TargetFormat{copilot}, false},
		{"claude/character-class-globs", []canonical.TargetFormat{copilot}, false},
		{"claude/duplicate-titles", []canonical.TargetFormat{copilot, codex}, false},
		{"codex/nested", all, true},
		{"copilot/basic", all, true},
		{"copilot/brace-globs", []canonical.TargetFormat{claude, codex}, false},
		{"copilot/character-class-globs", []canonical.TargetFormat{claude}, false},
		{"kiro/steering", all, true},
	}
}

// Validate both directions: no registered case may disappear, and no fixture
// directory or obsolete target snapshot may silently fall outside the suite.
func validateGoldenInventory(root string, cases []goldenCase) error {
	providers := []string{"canonical", "claude", "codex", "copilot", "kiro"}
	registered := map[string]bool{}
	for _, c := range cases {
		provider, name, ok := strings.Cut(c.name, "/")
		validProvider := false
		for _, p := range providers {
			validProvider = validProvider || provider == p
		}
		if !ok || !validProvider || name == "" || name == "." || name == ".." || strings.ContainsAny(name, "/\\") || registered[c.name] {
			return fmt.Errorf("invalid or duplicate golden case %q", c.name)
		}
		registered[c.name] = true
		if len(c.targets) == 0 {
			return fmt.Errorf("golden case %s has no targets", c.name)
		}
		allowed := map[string]bool{"expected-diagnostics.json": provider != "canonical", "expected-project": c.snapshotProject}
		for _, target := range c.targets {
			switch target {
			case canonical.TargetCopilot, canonical.TargetClaude, canonical.TargetCodex, canonical.TargetKiro:
			default:
				return fmt.Errorf("golden case %s has unsupported target %q", c.name, target)
			}
			prefix := "expected-" + string(target)
			if allowed[prefix] {
				return fmt.Errorf("golden case %s repeats target %s", c.name, target)
			}
			allowed[prefix] = true
			allowed[prefix+"-mappings.json"] = true
			allowed[prefix+"-diagnostics.json"] = true
			allowed["profile-"+string(target)+".json"] = true
		}
		entries, err := os.ReadDir(filepath.Join(root, c.name))
		if err != nil {
			return fmt.Errorf("golden case %s: %w", c.name, err)
		}
		for _, e := range entries {
			if (strings.HasPrefix(e.Name(), "expected-") || strings.HasPrefix(e.Name(), "profile-")) && !allowed[e.Name()] {
				return fmt.Errorf("golden case %s: undeclared snapshot/profile %s", c.name, e.Name())
			}
		}
	}
	for _, provider := range providers {
		entries, err := os.ReadDir(filepath.Join(root, provider))
		if err != nil {
			return err
		}
		for _, e := range entries {
			if e.IsDir() && !registered[provider+"/"+e.Name()] {
				return fmt.Errorf("unregistered golden case %s/%s", provider, e.Name())
			}
		}
	}
	return nil
}

// No diagnostic file means exactly zero diagnostics, not unchecked diagnostics.
// Only make golden can create a nonempty snapshot or remove an empty one.
func compareDiagnostics(t *testing.T, path string, diags []diagnostics.Diagnostic) {
	t.Helper()
	if len(diags) == 0 {
		if *updateGolden {
			if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
				t.Fatal(err)
			}
			return
		}
		if _, err := os.Stat(path); os.IsNotExist(err) {
			return
		} else if err != nil {
			t.Fatal(err)
		}
	}
	compareOrUpdate(t, path, diagnosticsJSON(t, diags))
}

// TestGoldenImportAndExport is the provider fixture suite: it imports each
// fixture, compares the canonical project and diagnostics, then compiles every
// requested target and compares the generated files.
func TestGoldenImportAndExport(t *testing.T) {
	cases := goldenCases()
	if err := validateGoldenInventory(testdataDir, cases); err != nil {
		t.Fatal(err)
	}
	for _, c := range cases {
		provider, _, _ := strings.Cut(c.name, "/")
		if provider == "canonical" {
			continue
		}
		format := canonical.TargetFormat(provider)
		if provider == "copilot" {
			format = canonical.TargetCopilot
		}
		t.Run(c.name, func(t *testing.T) {
			caseDir := filepath.Join(testdataDir, c.name)
			ws := materialize(t, filepath.Join(caseDir, "input"))
			ctx := context.Background()
			res, err := compiler.Import(ctx, ws, compiler.ImportOptions{
				Format: format, ProjectID: "prj_fixture", ProjectName: "Fixture",
			})
			if err != nil {
				t.Fatalf("import: %v", err)
			}
			if diagnostics.HasBlocking(res.Diagnostics) {
				t.Fatalf("golden imports must succeed; cover rejection with focused assertions: %+v", res.Diagnostics)
			}
			if c.snapshotProject {
				compareProjectTree(t, caseDir, res.Project)
			}
			compareDiagnostics(t, filepath.Join(caseDir, "expected-diagnostics.json"), res.Diagnostics)
			compileTargets(t, ctx, caseDir, res.Project, c.targets)
		})
	}
}

// TestGoldenCanonical compiles hand-authored canonical projects. These cover
// shapes no importer can produce, such as exclude patterns and disabled rules.
func TestGoldenCanonical(t *testing.T) {
	cases := goldenCases()
	if err := validateGoldenInventory(testdataDir, cases); err != nil {
		t.Fatal(err)
	}
	for _, c := range cases {
		caseName, ok := strings.CutPrefix(c.name, "canonical/")
		if !ok {
			continue
		}
		t.Run(caseName, func(t *testing.T) {
			caseDir := filepath.Join(testdataDir, c.name)
			data, err := os.ReadFile(filepath.Join(caseDir, "canonical.json"))
			if err != nil {
				t.Fatal(err)
			}
			project, err := canonical.UnmarshalProject(data)
			if err != nil {
				t.Fatalf("decode fixture project: %v", err)
			}
			if diags := canonical.Validate(project); diagnostics.HasBlocking(diags) {
				t.Fatalf("fixture project is invalid: %+v", diags)
			}
			compileTargets(t, context.Background(), caseDir, project, c.targets)
		})
	}
}

// compileTargets uses only the declared targets, including during regeneration.
func compileTargets(
	t *testing.T, ctx context.Context, caseDir string, project canonical.Project, targets []canonical.TargetFormat,
) {
	t.Helper()
	for _, format := range targets {
		target := string(format)
		profile := profiles.Default(format)
		if data, err := os.ReadFile(filepath.Join(caseDir, "profile-"+target+".json")); err == nil {
			profile, err = profiles.Unmarshal(data)
			if err != nil {
				t.Fatalf("decode profile for %s: %v", target, err)
			}
		} else if !os.IsNotExist(err) {
			t.Fatal(err)
		}
		result, err := compiler.Compile(ctx, project, compiler.CompileOptions{
			Target:  format,
			Profile: profile,
		})
		if err != nil {
			t.Fatalf("compile %s: %v", target, err)
		}
		outDir := filepath.Join(caseDir, "expected-"+target)
		if *updateGolden {
			if err := os.RemoveAll(outDir); err != nil {
				t.Fatal(err)
			}
		}
		for _, f := range result.Files {
			compareOrUpdate(t, filepath.Join(outDir, filepath.FromSlash(f.Path)), f.Content)
		}
		compareOrUpdate(t, filepath.Join(caseDir, "expected-"+target+"-mappings.json"),
			mappingsJSON(t, result.Mappings))
		compareDiagnostics(t, filepath.Join(caseDir, "expected-"+target+"-diagnostics.json"), result.Diagnostics)

		// Every generated file must be present in the fixture, and the fixture
		// must contain nothing extra.
		if !*updateGolden {
			assertSameFileSet(t, outDir, result.Files, target)
		}
	}
}

func assertSameFileSet(t *testing.T, dir string, files []adapters.GeneratedFile, target string) {
	t.Helper()
	want := map[string]struct{}{}
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, rerr := filepath.Rel(dir, path)
		if rerr != nil {
			return rerr
		}
		want[filepath.ToSlash(rel)] = struct{}{}
		return nil
	})
	if err != nil && !(os.IsNotExist(err) && len(files) == 0) {
		t.Fatal(err)
	}
	for _, f := range files {
		delete(want, f.Path)
	}
	extra := make([]string, 0, len(want))
	for path := range want {
		extra = append(extra, path)
	}
	sort.Strings(extra)
	for _, path := range extra {
		t.Errorf("target %s: fixture contains %s but the compiler did not generate it", target, path)
	}
}
